# do not touch this line
configVersion: 2

name: MatrixInfoApp
description: This app shows informations about all sensor on app dashboard
keywords: 'sensor, info, dash'

screens:
  - - temperatureSensor
    - humiditySensor
    - accelerometerSensor
    - gyroscopeSensor
    - uvSensor
    - pressureSensor
    - altitudeSensor

sensors:
  - temperature
  - humidity
  - accelerometer
  - gyroscope
  - uv
  - pressure
  - altitude

dataTypes:
  temperatureValue: float
  humidityValue: float
  accelerometerValue: float
  gyroscopeValue:
    x: float
    y: float
    z: float
  uvValue: float
  pressureValue: float
  altitudeValue: float

widgets:
  temperatureSensor:
    label: Temperature ºC
    display: digit
    key: temperatureValue
    push: false
    pull: true
    refresh: 60
  humiditySensor:
    label: Humidity %
    display: digit
    key: humidityValue
    push: false
    pull: true
    refresh: 60
  accelerometerSensor:
    label: Accelerometer
    display: digit
    key: accelerometerValue
    push: false
    pull: true
    refresh: 60
  gyroscopeSensor:
    label: Humidity %
    display: digit
    key:
      - x
      - y
      - z
    push: false
    pull: true
    refresh: 60
  uvSensor:
    label: UV Risk
    display: digit
    key: UValue
    push: false
    pull: true
    refresh: 60
  pressureSensor:
    label: Pressure
    display: digit
    key: pressureValue
    push: false
    pull: true
    refresh: 60
  altitudeSensor:
    label: Altitude
    display: digit
    key: altitudeValue
    push: false
    pull: true
    refresh: 60
