# do not touch this line
configVersion: 2

name: MatrixInfoApp
description: This app shows informations about all sensor on app dashboard
keywords: 'sensor, info, dash'

screens:
  - - sensorDetails

sensors:
  - temperature
  - humidity
  - gyroscope
  - uv
  - pressure
  - altitude

dataTypes:
  sensorValue:
    value: float
    sensorName: string

widgets:
  sensorDetails:
    type: sensorValue
    display: list-group
    groupBy: sensorName
    label: Sensor's details
    keys:
      - sensorName
      - value
