# do not touch this line
configVersion: 2

description: Fireworks at faces
keywords: ''
name: faceBoom
displayName: Face Boom

events:
  - r
  - s

services:
  faceTest:
    engine: detection
    type: face
