# do not touch this line
configVersion: 2

name: Clicking
description: >- STANDBY FOR NOW
  So, this app is very simple. We gonna have some buttons on dashboard, each
  button makes the leds blink in a determined color and show some information
  about each sensor
keywords: 'sensors click buttons '

screens:
  - - buttonsPage

widgets:
  buttonsPage:
    label: Sensors buttons
    control: button
    map:
    - event: buttonClick
      value: button click
    value: Just a button
