# do not touch this line
configVersion: 2

name: Clicking
description: >-
  So, this app is very simple. We gonna have some buttons on dashboard, each
  button makes the leds blink in a determined color and show some information
  about each sensor
keywords: 'sensors click buttons '

screens:
  - - buttonsPage
  - - information

widgets:
  buttonsPage:
    label: Sensors buttons
    control: button
    event: buttonInfo
    value: Just a button
