# do not touch this line
configVersion: 2

description: asdf
keywords: ''
name: pipelineTestCrash
shortName: pipelineTestCrash
displayName: Pipeline Test

dataTypes: 
  face: 
    isView: boolean
    isImpression: boolean
    age: integer
    gender: string
    emotion: string
    timestamp: integer
    dwellTime: float  

widgets:
  base:
    display: list
    keys: 
      - isView
      - isImpression
      - age
      - gender
      - emotion
      - timestamp
      - dwellTime
    label: "Test"
    type: face
  age:
    display: digit
    key: age
    format: avg
    label: Age
    type: face
  dwell:
    display: digit
    key: dwellTime
    format: avg
    label: "Dwell"
    type: face
  view:
    display: digit
    key: isView
    format: count
    label: "Views"
    type: face
  gender:
    display: list-group
    keys: gender
    format: count
    groupby: gender
    label: "Gender"
    type: face
  maxDwellTime:
    display: digit
    keys: dwellTime
    format: max
    label: "Max Dwell Time"
    type: face
  minDwellTime:
    display: digit
    keys: dwellTime
    format: min
    label: "Min Dwell Time"
    type: face
  totalDwellTime:
    display: digit
    keys: dwellTime
    format: sum
    label: "Total Dwell Time"
    type: face
    
  
screens: 
- - base
- - gender