# do not touch this line
configVersion: 2

description: recognition demo
keywords: cv
name: recogTest
displayName: Recog
galleryUrl: https://storage.googleapis.com/admobilize-assets/matrix-appstore-images-tmp/app-tn/recog-g.png
imageUrls:
  - https://storage.googleapis.com/admobilize-assets/matrix-appstore-images-tmp/app-tn/recog.png

events:
  - train
  - recog
  - reset
  - stopper
  
services:
  re:
    engine: recognition
    type: face

screens: 
  - - train
  - - recognize
  
widgets:
  train:
    event: train
    control: button
    label: 'Train your Face'
    value: 'Train'
  recognize:
    event: recog
    control: button
    label: Recognize Your Face
    value: Recognize
  
  
