name: clock
configVersion: 2
description: Basic clock application using LED array.
keywords: time, led

categories:
  - entertainment

imageUrls: 
  - https://storage.googleapis.com/admobilize-assets/matrix-appstore-images-tmp/app-tn/clock.jpg

galleryImageUrl: https://storage.googleapis.com/admobilize-assets/matrix-appstore-images-tmp/app-tn/clock-g.jpg
