# do not touch this line
configVersion: 2

description: test wakeword
keywords: ''
name: wordtest
shortName: wordtest
displayName: Wordtest

services:
  customListener:
    engine: voice
    wakeword: matrix
    phrases: 
      - shine blue
      - shine red
      - shine green
      - turn off