# do not touch this line
configVersion: 2

description: test the sensors
name: sensorTest
keywords:
  - development
  - testing
  - sensors
version: 1.0.3

sensors:
  - temperature
  - humidity
  - magnetometer
  - accelerometer
  - gyroscope
  - uv
  - pressure
  - altitude

dataTypes:
  temperature: float
  magnetometer:
    x: float
    y: float
    z: float
  humidity: float
  accelerometer:
    x: float
    y: float
    z: float
  gyroscope:
    yaw: float
    pitch: float
    roll: float
    x: float
    y: float
    z: float
  uv: float
  pressure: float
  altitude: float
