# do not touch this line
configVersion: 2

description: test the sensors fool
name: sensorTest

screens:
  - SensorsDetails

sensors:
  - temperature
  - humidity
  - accelerometer
  - gyroscope
  - uv
  - pressure
  - altitude

dataTypes:
  temperature: float
  humidity: float
  accelerometer: float
  gyroscope:
    x: float
    y: float
    z: float
  uv: float
  pressure: float
  altitude: float

widgets:
  SensorsDetails:
    label: Sensor's Details
    display: list-group
    type: device
